### ISSUE TITLE
Build failure with gcc7: lambda can’t have ‘this’ pointer captures

### ISSUE THREAD

**Issue by marguerite** [fcitx/fcitx5#174]
openSUSE Leap 15.1 has gcc7, and the build fails with:

<pre>
build'
[   63s] [ 39%] Building CXX object test/CMakeFiles/testdbus.dir/testdbus.cpp.o
[   63s] cd /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/build/test && /usr/bin/c++   -I/home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/build -I/home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/build/test -I/home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/src/lib/fcitx-utils/.. -I/home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/build/src/lib/fcitx-utils  -Wall -Wextra -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -O2 -g -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++1z -o CMakeFiles/testdbus.dir/testdbus.cpp.o -c /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp
[   63s] In file included from /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/src/lib/fcitx-utils/../fcitx-utils/dbus/bus.h:14:0,
[   63s]                  from /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp:10:
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp:70:10: warning: already captured 'this' in lambda expression
[   63s]          [this](int32_t v) { prop2 = v; });
[   63s]           ^
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/src/lib/fcitx-utils/../fcitx-utils/dbus/objectvtable.h:249:25: note: in definition of macro 'FCITX_OBJECT_VTABLE_WRITABLE_PROPERTY'
[   63s]          [this, method = SETMETHOD](::fcitx::dbus::Message &msg) {              \
[   63s]                          ^~~~~~~~~
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp: In lambda function:
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp:70:29: error: 'this' was not captured for this lambda function
[   63s]          [this](int32_t v) { prop2 = v; });
[   63s]                              ^
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/src/lib/fcitx-utils/../fcitx-utils/dbus/objectvtable.h:249:25: note: in definition of macro 'FCITX_OBJECT_VTABLE_WRITABLE_PROPERTY'
[   63s]          [this, method = SETMETHOD](::fcitx::dbus::Message &msg) {              \
[   63s]                          ^~~~~~~~~
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp:70:29: error: invalid use of non-static data member 'TestObject::prop2'
[   63s]          [this](int32_t v) { prop2 = v; });
[   63s]                              ^
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/src/lib/fcitx-utils/../fcitx-utils/dbus/objectvtable.h:249:25: note: in definition of macro 'FCITX_OBJECT_VTABLE_WRITABLE_PROPERTY'
[   63s]          [this, method = SETMETHOD](::fcitx::dbus::Message &msg) {              \
[   63s]                          ^~~~~~~~~
[   63s] /home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/test/testdbus.cpp:58:17: note: declared here
[   63s]      int prop2 = 1;
[   63s]                  ^
[   63s] make[2]: *** [test/CMakeFiles/testdbus.dir/build.make:66: test/CMakeFiles/testdbus.dir/testdbus.cpp.o] Error 1
[   63s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/fcitx5-5.0.3/build'
[   63s] make[1]: *** [CMakeFiles/Makefile2:3883: test/CMakeFiles/testdbus.dir/all] Error 2
</pre>

By changing the second ‘this’ to ‘&’, the testdbus.cpp builds. But I can not figure out why ‘this’ capture is not possible @csslayer 

This patch can make fcitx5 builds on openSUSE Leap 15.1, but I don’t know if ‘&’ capture introduces any unwanted stuff:

https://build.opensuse.org/package/view_file/home:MargueriteSu:branches:M17N/fcitx5/fcitx5-lambda.patch?expand=1

The build result before applying the patch(failure):

https://build.opensuse.org/package/live_build_log/home:MargueriteSu:branches:M17N/fcitx5/openSUSE_Leap_15.1/x86_64

After (success):

https://build.opensuse.org/package/live_build_log/M17N/fcitx5/openSUSE_Leap_15.1/x86_64

Please review 

M

**Comment by wengxt** [comment]
The bug is in the compiler, so I'm not willing to workaround it like that. I suggest you just keep it as a downstream patch. (Maybe rename it as fcitx5-gcc7.patch :) )
